#!/usr/local/bin/python3
import comtrade
import os
import os.path as op
import sys

helpinfo = "\ncomtrade can convert comtrade files to pic file or csv data file. \
The tool can also show the wave figure. Addionally, \
It can convert multiple files in the dir.\n\n\
Usage:\n\
  comtrade [options [args]] [file/dir]\n\n\
options:\n\
  -h: print the help infomation\n\
  -s: show the figure window\n\
  -f: set the file format convert to, with args specifying file format\n\n\
args:\n\
  format: pdf, png, eps, svg, ps, csv\n\n\
file/dir:\n\
  file: specify a couple of comtrade files\n\
  dir: specify a direction, convert the files in the direction\n\n\
Default:\n\
  default format is pdf.\n\n\
Example:\n\
  comtrade -f png xxx.cfg\n"

formatList = ['png', 'pdf', 'ps', 'svg', 'csv', 'eps']

def printinfo():
    print(helpinfo)
        
def initargs():
    """
    init the args dictionary
    """
    argdict = dict()
    argdict['-h'] = False
    argdict['-s'] = False
    argdict['-f'] = 'pdf'
    argdict['object'] = 'file'
    argdict['path'] = ''
    return argdict

def parseargs(argdict, args=sys.argv):
    """
    parse the sys.argv and get valid args
    1. argdict: the args dictionary
    2. args: sys.argv
    """
    length = len(args)
    for i in range(1, length):
        if args[i][0] == '-':
            if len(args[i]) == 2:
                if args[i] == '-h':
                    argdict['-h'] = True
                elif args[i] == '-s':
                    argdict['-s'] = True
                elif args[i] == '-f':
                    if i >= length - 1:
                        print("the option -f has no specified format, please check help info: comtrade -h")
                        sys.exit(1)
                    else:
                        if args[i+1] in formatList:
                            argdict['-f'] = args[i+1]
                        else:
                            print('the format is not supported, you can specify: png, pdf, eps, ps, svg and csv')
                            sys.exit(1)
                else:
                    print('unknown option: %s, please check help info: comtrade -h' % args[i])
                    sys.exit(1)
            else:
                print('the option %s is invalid! Get help info: comtrade -h' % args)
                sys.exit(1)
    if args[-1][0] == '-':
        if argdict['-h'] == False:
            print('have no valid file or direction, please check if specify a file or direction!\nmore info: comtrade -h')
            sys.exit(1)
        else:
            printinfo()
            sys.exit(0)
    fileordir = op.abspath(args[-1])
    if op.isdir(fileordir):
        argdict['object'] = 'dir'
    else:
        argdict['object'] = 'file'
    if not op.exists(fileordir):
        print('\nThe file doesn\'t exist, please select a valid contrade configuration file!\n')
        sys.exit(1)
    else:
        argdict['path'] = fileordir
    return argdict

def parsewave(wavefile):
    """
    parse the cfg file
    """
    parser = comtrade.ComtradeParser(wavefile)
    if parser.result != 'parsed':
        print('\nParse failed! Error: %s\n' % parser.result)
        sys.exit(1)
    parser.plot()
    return parser

def scancfgfile(dirpath):
    """
    list the files in dirpath, and get cfg files list
    """
    cfgfiles = list()
    files = os.listdir(dirpath)
    for each in files:
        if '.cfg' in each:
            cfgfiles.append(each)
    return cfgfiles

argdict = initargs()
argdict = parseargs(argdict, sys.argv)

if argdict['-h'] == True:
    printinfo()
    sys.exit(0)

if argdict['object'] == 'file':
    print('parsing the file: %s ...' % argdict['path'])
    parser = parsewave(argdict['path'])
    parser.savefig(argdict['-f'])
    print('parsed!')
    if argdict['-s'] == True:
        parser.show()
else:
    cfgfiles = scancfgfile(argdict['path'])
    if len(cfgfiles) == 0:
        print("%s has no comtrade file!" % argdict['path'])
        sys.exit(0)
    print("parsing the %d file:" % len(cfgfiles))
    for cfgfile in cfgfiles:
        print("  %s ..." % cfgfile)
        parser = parsewave(cfgfile)
        parser.savefig(argdict['-f'])
    print('Finished!')

